/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[2];

//Textdraws
PublicTD[0] = TextDrawCreate(310.000000, 316.000000, "ACEITAR");
TextDrawFont(PublicTD[0], 2);
TextDrawLetterSize(PublicTD[0], 0.258332, 1.750000);
TextDrawTextSize(PublicTD[0], 16.500000, 90.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 1);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 152);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 1);

PublicTD[1] = TextDrawCreate(172.000000, 337.000000, "~r~Marcos: ~w~ Ola sobrevivente, pode me ajudar?, meu veiculo esta danificado e eu preciso de um motor para consertar-lo");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.287500, 2.199998);
TextDrawTextSize(PublicTD[1], 455.000000, 322.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 2);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 129);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
