/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][12];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 104.000000, 143.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.662499, 26.499942);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 159.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 9109759);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], -764862721);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 104.000000, 115.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.662499, 25.549957);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 298.500000, 159.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -294256385);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 741092607);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 104.000000, 143.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.662499, 25.549957);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 298.500000, 159.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -294256385);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 303174399);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 36.000000, 120.000000, "INFORMACOES");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.449999, 1.649999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], -294256385);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 100.000000, 349.000000, "DISCORD");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 16.500000, 90.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 200);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 28.000000, 155.000000, "DISCORD: discord.gg/TEWqFRP");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 28.000000, 176.000000, "SITE/LOJA: www.nextdaysurvival.rf.gd");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 28.000000, 199.000000, "Adicionado Temporadas");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 28.000000, 221.000000, "Adicionado sistemas de bases");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 28.000000, 241.000000, "Adicionado novos LOOTs");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 28.000000, 264.000000, "Adicionado Zonas toxicas");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.245831, 1.500000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 2);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 44.000000, 317.000000, "Versao: 1.5.0");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.379166, 1.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
