/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[11];

//Textdraws
PublicTD[0] = TextDrawCreate(322.000000, 1.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.600000, 53.850002);
TextDrawTextSize(PublicTD[0], 298.500000, 685.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 241);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(210.000000, 12.000000, "nextday ~r~survival");
TextDrawFont(PublicTD[1], 0);
TextDrawLetterSize(PublicTD[1], 1.104166, 4.900001);
TextDrawTextSize(PublicTD[1], 490.500000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(367.000000, -29.000000, "Preview_Model");
TextDrawFont(PublicTD[2], 5);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[2], 112.500000, 150.000000);
TextDrawSetOutline(PublicTD[2], 0);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -16776961);
TextDrawBackgroundColor(PublicTD[2], 0);
TextDrawBoxColor(PublicTD[2], 0);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);
TextDrawSetPreviewModel(PublicTD[2], 19836);
TextDrawSetPreviewRot(PublicTD[2], -63.000000, 0.000000, -20.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[2], 19, 19);

PublicTD[3] = TextDrawCreate(403.000000, 40.000000, "1.5.0");
TextDrawFont(PublicTD[3], 0);
TextDrawLetterSize(PublicTD[3], 0.474999, 1.899999);
TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(324.000000, 164.000000, "_");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.600000, 25.300003);
TextDrawTextSize(PublicTD[4], 298.500000, 140.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 2);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 202);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(315.000000, 75.000000, "_");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.600000, -0.649995);
TextDrawTextSize(PublicTD[5], 298.500000, 161.500000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 2);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], -121);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(324.000000, 220.000000, "jogar");
TextDrawFont(PublicTD[6], 2);
TextDrawLetterSize(PublicTD[6], 0.333332, 2.049999);
TextDrawTextSize(PublicTD[6], 16.500000, 90.500000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 2);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 1296911696);
TextDrawUseBox(PublicTD[6], 1);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 1);

PublicTD[7] = TextDrawCreate(294.000000, 172.000000, "MENU");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 1);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(324.000000, 261.000000, "CREDITOS");
TextDrawFont(PublicTD[8], 2);
TextDrawLetterSize(PublicTD[8], 0.333332, 2.049999);
TextDrawTextSize(PublicTD[8], 16.500000, 90.500000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 2);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 1296911696);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 1);

PublicTD[9] = TextDrawCreate(324.000000, 302.000000, "DISCORD");
TextDrawFont(PublicTD[9], 2);
TextDrawLetterSize(PublicTD[9], 0.333332, 2.049999);
TextDrawTextSize(PublicTD[9], 16.500000, 90.500000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 2);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 1296911696);
TextDrawUseBox(PublicTD[9], 1);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 1);

PublicTD[10] = TextDrawCreate(393.000000, 377.000000, "Todos os direitos reservados a NextDay - Survival. 2020");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.137500, 0.950000);
TextDrawTextSize(PublicTD[10], 358.500000, 17.000000);
TextDrawSetOutline(PublicTD[10], 1);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 3);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
